version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '0.0.0.0:3000:3000'
    restart: unless-stopped
    container_name: landing-yachay-app
    environment:
      - PORT=3000
      - NODE_ENV=production